namespace: demo-app
replicas: 1
image:
  repository: sajit21/flask-app
  tag: ae755a36ef666c2bb6cd3fb6ff2d1cacd5972060
containerPort: 5000
service:
  nodePort: 30088
hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
resources:
  requests:
    cpu: 100m
  limits:
    cpu: 500m
