namespace: demo-app
replicas: 1
image:
  repository: sajit21/flask-app
  tag: 13f59e534f2fafd8269479991b4693f3083e23c3
containerPort: 5000
service:
  nodePort: 30088
hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
resources:
  requests:
    cpu: 100m
  limits:
    cpu: 500m
