namespace: demo-app
replicas: 1

image:
  repository: sajit21/flask-app
  tag: deb1e8e189d329a30d68cb236e6cf14632e4f3a8

containerPort: 5000

service:
  nodePort: 30088

hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 500m
