apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.fullname" . }}-service
  namespace: {{ include "demo-app.namespace" . }}

spec:
  selector:
    app: {{ include "demo-app.name" . }}

  ports:
    - protocol: TCP
      port: 5000
      targetPort: {{ include "demo-app.containerPort" . }}
      nodePort: {{ include "demo-app.service.nodePort" . }}

  type: NodePort
